FileVersion = 1
Dependencies = {corlib = "*", BeefToml = "*", CowieCLI = "*"}

[Project]
Name = "Grill"
StartupObject = "Grill.Program"

[Platform.Windows]
FileVersion = "0.0.1"
ProductVersion = "0.0.1"

[Configs.Debug.Win64]
BeefLibType = "Static"
PostBuildCmds = ["xcopy $(TargetDir)\\$(ProjectName).exe $(ProjectDir)\\bin /y"]
DebugCommand = "$(ProjectDir)\\bin\\$(ProjectName).exe"
DebugCommandArguments = "init"
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Debug.Win32]
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Debug_add.Win64]
BeefLibType = "Static"
PostBuildCmds = ["xcopy $(TargetDir)\\$(ProjectName).exe $(ProjectDir)\\bin /y"]
DebugCommand = "$(ProjectDir)\\bin\\$(ProjectName).exe"
DebugCommandArguments = "add steak.logging --debug"
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Debug_add.Win32]
BeefLibType = "Static"
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Debug_help.Win64]
BeefLibType = "Static"
PostBuildCmds = ["xcopy $(TargetDir)\\$(ProjectName).exe $(ProjectDir)\\bin /y"]
DebugCommand = "$(ProjectDir)\\bin\\$(ProjectName).exe"
DebugCommandArguments = "--help"
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Debug_help.Win32]
BeefLibType = "Static"
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Debug_init.Win64]
BeefLibType = "Static"
PostBuildCmds = ["xcopy $(TargetDir)\\$(ProjectName).exe $(ProjectDir)\\bin /y"]
DebugCommand = "$(ProjectDir)\\bin\\$(ProjectName).exe"
DebugCommandArguments = "init"
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS", "DEBUG"]

[Configs.Debug_init.Win32]
BeefLibType = "Static"
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Debug_install.Win64]
BeefLibType = "Static"
PostBuildCmds = ["xcopy $(TargetDir)\\$(ProjectName).exe $(ProjectDir)\\bin /y"]
DebugCommand = "$(ProjectDir)\\bin\\$(ProjectName).exe"
DebugCommandArguments = "install mypackage --debug"
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS", "DEBUG"]

[Configs.Debug_install.Win32]
BeefLibType = "Static"
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Paranoid.Win64]
PostBuildCmds = ["xcopy $(TargetDir)\\$(ProjectName).exe $(ProjectDir)\\bin /y"]
DebugCommand = "$(ProjectDir)\\bin\\$(ProjectName).exe"
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Paranoid.Win32]
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Release.Win64]
PostBuildCmds = ["xcopy $(TargetDir)\\$(ProjectName).exe $(ProjectDir)\\bin /y"]
DebugCommand = "$(ProjectDir)\\bin\\$(ProjectName).exe"
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Release.Win32]
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Test.Win64]
PostBuildCmds = ["xcopy $(TargetDir)\\$(ProjectName).exe $(ProjectDir)\\bin /y"]
DebugCommand = "$(ProjectDir)\\bin\\$(ProjectName).exe"
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Test.Win32]
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]
