FileVersion = 1
Dependencies = {corlib = "*", BeefToml = "*", CowieCLI = "*", JSON_Beef = "*"}

[Project]
Name = "Grill"
StartupObject = "Grill.Program"

[Platform.Windows]
FileVersion = "0.0.1"
ProductVersion = "0.0.1"

[Configs.Debug.Win64]
BeefLibType = "Static"
PostBuildCmds = ["if not exist \"$(TargetDir)/Git\" ( xcopy \"$(ProjectDir)\\bin\" \"$(TargetDir)\" /e /c /i /q /y )", "del /F/Q/S \"$(TargetDir)\\Packages\"", "rmdir /q /s \"$(TargetDir)\\Packages\""]
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Debug.Win32]
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Release.Win64]
PostBuildCmds = ["if not exist \"$(TargetDir)/Git\" ( xcopy \"$(ProjectDir)\\bin\" \"$(TargetDir)\" /e /c /i /q /y )", "del /F/Q/S \"$(TargetDir)\\Packages\"", "rmdir /q /s \"$(TargetDir)\\Packages\""]
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Release.Win32]
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Paranoid.Win64]
PostBuildCmds = ["if not exist \"$(TargetDir)/Git\" ( xcopy \"$(ProjectDir)\\bin\" \"$(TargetDir)\" /e /c /i /q /y )", "del /F/Q/S \"$(TargetDir)\\Packages\"", "rmdir /q /s \"$(TargetDir)\\Packages\""]
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Paranoid.Win32]
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Test.Win64]
PostBuildCmds = ["if not exist \"$(TargetDir)/Git\" ( xcopy \"$(ProjectDir)\\bin\" \"$(TargetDir)\" /e /c /i /q /y )", "del /F/Q/S \"$(TargetDir)\\Packages\"", "rmdir /q /s \"$(TargetDir)\\Packages\""]
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Test.Win32]
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs."grill add".Win64]
BeefLibType = "Static"
PostBuildCmds = ["if not exist \"$(TargetDir)/Git\" ( xcopy \"$(ProjectDir)\\bin\" \"$(TargetDir)\" /e /c /i /q /y )", "del /F/Q/S \"$(TargetDir)\\Packages\"", "rmdir /q /s \"$(TargetDir)\\Packages\""]
DebugCommandArguments = "add steak.logging -debug"
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs."grill add".Win32]
BeefLibType = "Static"
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs."grill install".Win64]
BeefLibType = "Static"
PostBuildCmds = ["if not exist \"$(TargetDir)/Git\" ( xcopy \"$(ProjectDir)\\bin\" \"$(TargetDir)\" /e /c /i /q /y )", "if exist \"$(TargetDir)\\Packages\" ( del /f /q /s \"$(TargetDir)\\Packages\" >NUL )", "if exist \"$(TargetDir)\\Packages\" ( rmdir /q /s \"$(TargetDir)\\Packages\" )"]
DebugCommandArguments = "install mypackage --debug"
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS", "DEBUG"]

[Configs."grill install".Win32]
BeefLibType = "Static"
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs."grill --help".Win64]
BeefLibType = "Static"
PostBuildCmds = ["if not exist \"$(TargetDir)/Git\" ( xcopy \"$(ProjectDir)\\bin\" \"$(TargetDir)\" /e /c /i /q /y )", "del /F/Q/S \"$(TargetDir)\\Packages\"", "rmdir /q /s \"$(TargetDir)\\Packages\""]
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs."grill --help".Win32]
BeefLibType = "Static"
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]
