[package]
name = "grill"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34"
reqwest = "0.11"
anyhow = "1.0"
# git2-v0.13 will sometimes compile libgit2-sys even without changes
git2 = "0.12"
dirs = "4.0"
rm_rf = "0.6"
url = "2.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
dialoguer = "0.9"
fs_extra = "1.2"
